### ISSUE TITLE
Request for an additional package

### ISSUE THREAD

**Issue by czopluoglu** [drivendataorg/literacy-screening-runtime#4]
Can you please add the Levenshtein package to the docker container?

https://pypi.org/project/python-Levenshtein/

Thank you.

**Comment by ejm714** [comment]
Hi @czopluoglu, typically I'd ask you follow the instructions in the README for opening a PR that adds a package to the runtime: https://github.com/drivendataorg/literacy-screening-runtime?tab=readme-ov-file#updating-runtime-packages. But since our team will be out shortly for the holidays, I went ahead and submitted a PR to do this so we can get this merged in today (https://github.com/drivendataorg/literacy-screening-runtime/pull/6)
